#!/bin/bash

echo "🚀 部署到 GitHub Pages 指南"
echo "================================"
echo ""
echo "📋 请按以下步骤操作："
echo ""
echo "1️⃣  在 GitHub 上创建新仓库"
echo "   访问: https://github.com/new"
echo "   仓库名建议: labpage 或 your-username.github.io"
echo ""
echo "2️⃣  运行以下命令推送代码："
echo ""
echo "   git remote add origin https://github.com/YOUR-USERNAME/YOUR-REPO-NAME.git"
echo "   git branch -M main"
echo "   git add ."
echo "   git commit -m \"Add GitHub Pages deployment configuration\""
echo "   git push -u origin main"
echo ""
echo "3️⃣  在 GitHub 仓库中启用 Pages："
echo "   - 进入仓库 Settings → Pages"
echo "   - Source 选择 'GitHub Actions'"
echo "   - 等待自动部署完成（约 2-3 分钟）"
echo ""
echo "4️⃣  访问你的网站："
echo "   https://YOUR-USERNAME.github.io/YOUR-REPO-NAME/"
echo ""
echo "================================"
echo ""
echo "⚠️  重要提示："
echo ""
echo "如果你的仓库名不是 username.github.io 格式，"
echo "需要编辑 next.config.js，取消注释 basePath 并设置为你的仓库名："
echo ""
echo "   basePath: '/YOUR-REPO-NAME',"
echo ""
echo "================================"
echo ""
echo "💡 推荐使用 Vercel（更简单）："
echo ""
echo "1. 访问 https://vercel.com"
echo "2. 用 GitHub 登录"
echo "3. Import 你的仓库"
echo "4. 点击 Deploy"
echo "5. 完成！（3 分钟搞定）"
echo ""
echo "================================"
